#!/usr/bin/env bash

# ===================================================================================
#
# build-plugins.sh
#
# Description:
#   This script builds a single, all-in-one Velero image that includes all
#   specified plugins pre-loaded into the /plugins directory. It uses a
#   multi-stage Docker build to handle "distroless" Velero base images that
#   lack a shell, ensuring correct file permissions and ownership.
#
#   The resulting image eliminates the need for init containers, simplifying
#   Kubernetes deployments.
#
# Usage:
#   ./build-plugins.sh --config <file_path> <output_image_name:tag> [--platform <platforms>] [--push]
#
# Requirements:
#   - A config file specifying the Velero base image and all desired plugins.
#   - bash v3.2+
#   - A container runtime (Docker or Podman) installed and in the PATH.
#
# ===================================================================================

# --- Script Configuration and Best Practices ---

# Exit immediately if a command exits with a non-zero status.
set -e
# Treat unset variables as an error and prevent them from expanding to an empty string.
set -u
# Propagate the exit code of the first failing command in a pipeline.
set -o pipefail

# --- Global Variables ---

# An array to hold the final list of plugins to be processed.
# Each entry is a pipe-separated string: "name|image:tag|/path/to/binary"
PLUGINS_TO_PROCESS=()
# The Velero base image that will be used for the final image.
VELERO_BASE_IMAGE=""
# The container runtime command to use (auto-detected as 'docker' or 'podman').
CONTAINER_RUNTIME=""
# The platforms to build for (default: linux/amd64)
PLATFORMS="linux/amd64"
# Whether to push the image after build
PUSH_IMAGE=false
# The path to the temporary Dockerfile generated by the script.
DOCKERFILE=""

# --- Color-coded Logging for Readability ---
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[0;33m'
readonly RED='\033[0;31m'
readonly RESET='\033[0m'

# Logging functions for different message levels.
log_info()  { echo -e "${GREEN}INFO:${RESET}  $1"; }
log_warn()  { echo -e "${YELLOW}WARN:${RESET}  $1"; }
log_error() { echo -e "${RED}ERROR:${RESET} $1" >&2; }

# --- Script Functions ---

#
# cleanup()
#
# Ensures that the temporary Dockerfile is always removed when the script exits,
# whether it succeeds, fails, or is interrupted by a signal.
# This function is registered with a 'trap' command in main().
#
cleanup() {
    # Check if the DOCKERFILE variable was set and if the file exists.
    if [[ -n "${DOCKERFILE-}" && -f "$DOCKERFILE" ]]; then
        log_info "Cleaning up temporary Dockerfile: $DOCKERFILE"
        rm -f "$DOCKERFILE"
    fi
}

#
# usage()
#
# Displays the help message for the script.
#
usage() {
    # Using a here document for a clean, multi-line message.
    cat <<EOF

Usage: $(basename "$0") --config FILE <output_image_name:tag> [--platform PLATFORMS] [--push]

Builds a single, all-in-one Velero image with plugins pre-loaded.

Required Arguments:
  --config FILE            Path to a .ini configuration file that specifies the
                           Velero base image and all desired plugins.
  output_image_name:tag    The name and tag for the final container image
                           (e.g., 'my-registry/velero-with-plugins:v1.14').


Options:
    --platform PLATFORMS     Comma-separated list of platforms to build for (default: linux/amd64,linux/arm64).
    --push                   Push the built image to the registry (required for multiarch manifest).
    --help                   Display this help message and exit.

.ini File Format:
  [velero]
  image = registry/velero:tag

  [plugin:short-name]
  image = registry/plugin-image:tag
  path  = /path/to/binary/in/plugin/image
EOF
}

#
# parse_config_file(config_file_path)
#
# Reads a specified .ini file, parses it, and validates its contents.
# This version is compatible with Bash 3.2+ and avoids features like
# associative arrays and problematic regex captures.
#
# Arguments:
#   $1 - The path to the configuration file.
#
parse_config_file() {
    local config_file="$1"
    log_info "Parsing configuration from '$config_file'..."

    # Local variables to track the state of the parser.
    local parsed_plugins=()
    local current_section=""
    local current_image=""
    local current_path=""
    local plugin_name=""
    local line_num=0

    # Read the file line by line to handle multi-line INI sections correctly.
    while IFS= read -r line || [[ -n "$line" ]]; do
        line_num=$((line_num + 1))
        # Trim leading/trailing whitespace from the line for robust parsing.
        line=$(echo "$line" | sed 's/^[ \t]*//;s/[ \t]*$//')

        # Ignore empty lines and comments (lines starting with # or ;).
        if [[ -z "$line" || "$line" =~ ^[#\;] ]]; then
            continue
        fi

        # Check for a new section header, e.g., [plugin:aws] or [velero].
        if [[ "$line" =~ ^\[.*\]$ ]]; then
            # Before starting a new section, validate and save the previous one if it was a plugin.
            if [[ "$current_section" =~ ^plugin: && -n "$current_image" && -n "$current_path" ]]; then
                plugin_name=${current_section#plugin:}
                parsed_plugins+=("${plugin_name}|${current_image}|${current_path}")
            fi

            # Reset state for the new section, using sed for safe, portable parsing.
            current_section=$(echo "$line" | sed 's/\[\(.*\)\]/\1/')
            current_image=""
            current_path=""

        # Check for an 'image' key.
        elif [[ "$line" =~ ^image[[:space:]]*=[[:space:]]*(.*)$ ]]; then
            # Using sed to reliably extract the value after '='
            current_image=$(echo "$line" | sed 's/image[[:space:]]*=[[:space:]]*//')
            if [[ "$current_section" == "velero" ]]; then
                VELERO_BASE_IMAGE="$current_image"
            fi
            
        # Check for a 'path' key.
        elif [[ "$line" =~ ^path[[:space:]]*=[[:space:]]*(.*)$ ]]; then
            if [[ ! "$current_section" =~ ^plugin: ]]; then
                log_error "Found 'path' key outside of a [plugin:...] section at line $line_num in '$config_file'."
                exit 1
            fi
            current_path=$(echo "$line" | sed 's/path[[:space:]]*=[[:space:]]*//')
            
        # If a line is not a section, key, or comment, it's an error.
        else
            log_error "Malformed line in '$config_file' at line $line_num: '$line'"
            exit 1
        fi
    done < "$config_file"

    # After the loop, save the very last plugin from the file if it's complete.
    if [[ "$current_section" =~ ^plugin: && -n "$current_image" && -n "$current_path" ]]; then
        plugin_name=${current_section#plugin:}
        parsed_plugins+=("${plugin_name}|${current_image}|${current_path}")
    fi

    # Final validation of the parsed content.
    if [[ -z "$VELERO_BASE_IMAGE" ]]; then
        log_error "Configuration file '$config_file' must contain a [velero] section with an 'image' key."
        exit 1
    fi
    if [ ${#parsed_plugins[@]} -eq 0 ]; then
        log_warn "No [plugin:...] sections were found in '$config_file'. Building image with no additional plugins."
    fi
    
    # Populate the global variable with the final list.
    PLUGINS_TO_PROCESS=("${parsed_plugins[@]}")
}

#
# main()
#
# The main execution flow of the script.
#
main() {
    # Register the cleanup function to run on script exit or interruption.
    trap cleanup EXIT SIGINT SIGTERM
    
    local config_file=""
    local output_image=""
    local image_version=""

    # Gracefully handle the case of no arguments.
    if [[ $# -eq 0 ]]; then
        usage
        exit 1
    fi
    
    # Parse command-line arguments.
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --config)
                if [ -z "${2-}" ]; then log_error "--config requires a file path."; usage; exit 1; fi
                config_file="$2"
                shift 2
                ;;
            --platform)
                if [ -z "${2-}" ]; then log_error "--platform requires a value."; usage; exit 1; fi
                PLATFORMS="$2"
                shift 2
                ;;
            --push)
                PUSH_IMAGE=true
                shift
                ;;
            --help)
                usage
                exit 0
                ;;
            -* )
                log_error "Unknown option: $1"; usage; exit 1
                ;;
            *)
                if [[ -n "$output_image" ]]; then log_error "Only one output image name is allowed."; usage; exit 1; fi
                output_image="$1"
                shift
                ;;
        esac
    done

    # --- Validation of Inputs ---
    if [[ -z "$config_file" ]]; then log_error "The --config FILE argument is mandatory."; usage; exit 1; fi
    if [[ -z "$output_image" ]]; then log_error "An output image name and tag are required."; usage; exit 1; fi
    if ! [[ "$output_image" =~ .*:.* ]]; then log_error "The output image name must include a tag (e.g., 'my-image:latest')."; exit 1; fi
    if [[ ! -f "$config_file" ]]; then log_error "Configuration file not found: '$config_file'"; exit 1; fi
    image_version="${output_image##*:}"

    # --- Prerequisite Checks ---

    if command -v docker &>/dev/null; then CONTAINER_RUNTIME="docker"; elif command -v podman &>/dev/null; then CONTAINER_RUNTIME="podman"; else log_error "Neither 'docker' nor 'podman' command found."; exit 1; fi
    log_info "Using container runtime: $CONTAINER_RUNTIME"

    # Check for buildx if using docker
    if [[ "$CONTAINER_RUNTIME" == "docker" ]]; then
        if ! docker buildx version &>/dev/null; then
            log_error "Docker Buildx is required for multiarch builds"
            exit 1
        fi
    fi

    # --- Core Logic ---
    parse_config_file "$config_file"
    DOCKERFILE=$(mktemp Dockerfile.XXXXXX)
    log_info "Generating efficient Dockerfile at '$DOCKERFILE'..."

    # Step 1: Define all the source stages for the plugins. This allows us to
    # reference them later in the final stage.
    local index=0
    for plugin_info in "${PLUGINS_TO_PROCESS[@]}"; do
        IFS='|' read -r plugin_name plugin_image plugin_path <<< "$plugin_info"
        local stage_name="plugin_stage_${index}"
        log_info "Adding stage for '$plugin_name' from image '$plugin_image'."
        cat <<EOF >> "$DOCKERFILE"
# --- Stage for ${plugin_name} ---
FROM ${plugin_image} AS ${stage_name}
EOF
        index=$((index + 1))
    done

    # Step 2: Create an intermediate stage based on a shell-enabled image (alpine)
    # to prepare the plugins directory with the correct permissions. This is the
    # key to working with a distroless final base image.
    cat <<EOF >> "$DOCKERFILE"

# --- Intermediate stage to prepare plugins ---
FROM alpine:latest AS plugins-prep

# Create the plugins directory
RUN mkdir -p /plugins
EOF

    # Step 3: Copy all plugin binaries into this intermediate stage.
    index=0
    for plugin_info in "${PLUGINS_TO_PROCESS[@]}"; do
        IFS='|' read -r plugin_name _ plugin_path <<< "$plugin_info"
        local stage_name="plugin_stage_${index}"
        log_info "Copying '$plugin_path' from stage '$stage_name' into the prep stage."
        cat <<EOF >> "$DOCKERFILE"
COPY --from=${stage_name} ${plugin_path} /plugins/
EOF
        index=$((index + 1))
    done
    
    # Step 4: Set the correct ownership and permissions in the intermediate stage.
    # This is done here because the final distroless image does not contain 'chown' or 'chmod'.
    cat <<EOF >> "$DOCKERFILE"

# Set ownership for the 'velero' user (UID 1001), which is the default in the official Velero image.
RUN chown -R 1001:1001 /plugins

# Ensure all plugin binaries are executable.
RUN chmod +x /plugins/*
EOF
    
    # Step 5: Define the final stage using the Velero image as the base.
    cat <<EOF >> "$DOCKERFILE"

# --- Final Stage ---
# Use the specified (distroless) Velero image as the base.
FROM ${VELERO_BASE_IMAGE}

ARG VERSION

LABEL name="CloudCasa Velero" \
    maintainer="support@cloudcasa.io" \
    vendor="Catalogic Software" \
    version="\${VERSION}" \
    release="\${VERSION}" \
    summary="CloudCasa Velero" \
    description="Velero container built on Red Hat UBI. Intended for use with the CloudCasa Operator on OpenShift clusters."

# Now, copy the fully prepared and permissioned /plugins directory
# from our intermediate stage. This single COPY command doesn't require a shell.
COPY --from=plugins-prep /plugins /plugins

# Include project license file in the image.
COPY LICENSE /licenses/LICENSE
EOF

    # Display the generated Dockerfile for transparency and debugging.
    echo -e "\n--- Generated Dockerfile ---"
    cat "$DOCKERFILE"
    echo "--------------------------"

    # --- Image Build ---

    log_info "Building the combined image as '$output_image' for platforms: $PLATFORMS ..."
    if [[ "$CONTAINER_RUNTIME" == "docker" ]]; then
        BUILD_CMD=(docker buildx build --platform "$PLATFORMS" --build-arg "VERSION=$image_version" -f "$DOCKERFILE" -t "$output_image" .)
        if $PUSH_IMAGE; then
            BUILD_CMD+=(--push)
        else
            BUILD_CMD+=(--load)
        fi
        log_info "Running: ${BUILD_CMD[*]}"
        "${BUILD_CMD[@]}"
    else
        log_warn "multiarch build is not fully supported for container runtime: $CONTAINER_RUNTIME. Building for default architecture only."
        "$CONTAINER_RUNTIME" build --build-arg "VERSION=$image_version" -f "$DOCKERFILE" -t "$output_image" .
    fi

    # --- Success Message ---
    log_info "----------------------------------------------------------------"
    log_info "SUCCESS: All-in-one image '$output_image' built successfully."
    log_info "----------------------------------------------------------------"
}

# --- Script Entrypoint ---
# Call the main function with all the script's arguments.
main "$@"
