# Configuration for building the combined Velero plugin image.
# path = The exact path to the binary inside the source image.

[plugin:aws]
image = catalogicsoftware/velero-plugin-for-aws:v1.10.0.3
path = /plugins/velero-plugin-for-aws

[plugin:gcp]
image = catalogicsoftware/velero-plugin-for-gcp:v1.10.0.2
path = /plugins/velero-plugin-for-gcp

[plugin:azure]
image = velero/velero-plugin-for-microsoft-azure:v1.10.0
path = /plugins/velero-plugin-for-microsoft-azure

[plugin:kubevirt]
image = catalogicsoftware/kubevirt-velero-plugin:v0.7.1.1
path = /plugins/kubevirt-velero-plugin

[plugin:amds]
image = catalogicsoftware/amds-veleroplugin:3.1.0-rc.928
path = /plugins/catalogicsoftware-velero-plugin

[velero]
image = catalogicsoftware/velero:v1.14.0.29
